version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:14.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test:coverage
      - run: npm run lint
workflows:
  on_commit:
    jobs:
      - test          